const listOfCivs = [
  {
    civ: "Babylon",
    tier: 1,
    bias: "Avoid Tundra",
    icon: require("./images/civIcons/babylon.png"),
  },
  {
    civ: "Egypt",
    tier: 1,
    bias: "Avoid Forest & Jungle",
    icon: require("./images/civIcons/egypt.png"),
  },
  {
    civ: "England",
    tier: 1,
    bias: "Coast",
    icon: require("./images/civIcons/england.png"),
  },
  {
    civ: "Ethopia",
    tier: 1,
    bias: "None",
    icon: require("./images/civIcons/ethiopia.png"),
  },
  {
    civ: "Inca",
    tier: 1,
    bias: "Hills",
    icon: require("./images/civIcons/inca.png"),
  },
  {
    civ: "Korea",
    tier: 1,
    bias: "Coast",
    icon: require("./images/civIcons/korea.png"),
  },
  {
    civ: "Persia",
    tier: 1,
    bias: "None",
    icon: require("./images/civIcons/persia.png"),
  },
  {
    civ: "Poland",
    tier: 1,
    bias: "Plains",
    icon: require("./images/civIcons/poland.png"),
  },
  {
    civ: "Huns",
    tier: 1,
    bias: "Avoid Forest & Jungle",
    icon: require("./images/civIcons/huns.png"),
  },
  {
    civ: "Maya",
    tier: 1,
    bias: "None",
    icon: require("./images/civIcons/maya.png"),
  },
  {
    civ: "Arabia",
    tier: 2,
    bias: "Desert",
    icon: require("./images/civIcons/arabia.png"),
  },
  {
    civ: "Aztec",
    tier: 2,
    bias: "Jungle",
    icon: require("./images/civIcons/aztec.png"),
  },
  {
    civ: "China",
    tier: 2,
    bias: "None",
    icon: require("./images/civIcons/china.png"),
  },
  {
    civ: "Greece",
    tier: 2,
    bias: "None",
    icon: require("./images/civIcons/greece.png"),
  },
  {
    civ: "Russia",
    tier: 2,
    bias: "Tundra",
    icon: require("./images/civIcons/russia.png"),
  },
  {
    civ: "Shoshone",
    tier: 2,
    bias: "None",
    icon: require("./images/civIcons/shoshone.png"),
  },
  {
    civ: "Spain",
    tier: 2,
    bias: "Coast",
    icon: require("./images/civIcons/spain.png"),
  },
  {
    civ: "Zulu",
    tier: 2,
    bias: "Avoid Jungle",
    icon: require("./images/civIcons/zulu.png"),
  },
  {
    civ: "Byzantium",
    tier: 3,
    bias: "Coast",
    icon: require("./images/civIcons/byzantine.png"),
  },
  {
    civ: "Celts",
    tier: 3,
    bias: "Forest",
    icon: require("./images/civIcons/celts.png"),
  },
  {
    civ: "Germany",
    tier: 3,
    bias: "None",
    icon: require("./images/civIcons/germany.png"),
  },
  {
    civ: "India",
    tier: 3,
    bias: "Grassland",
    icon: require("./images/civIcons/india.png"),
  },
  {
    civ: "Indonesia",
    tier: 3,
    bias: "Coast",
    icon: require("./images/civIcons/indonesia.png"),
  },
  {
    civ: "Mongolia",
    tier: 3,
    bias: "Plains",
    icon: require("./images/civIcons/mongolia.png"),
  },
  {
    civ: "Rome",
    tier: 3,
    bias: "None",
    icon: require("./images/civIcons/rome.png"),
  },
  {
    civ: "Siam",
    tier: 3,
    bias: "Avoid Forest",
    icon: require("./images/civIcons/siam.png"),
  },
  {
    civ: "Songhai",
    tier: 3,
    bias: "Avoid Tundra",
    icon: require("./images/civIcons/songhai.png"),
  },
  {
    civ: "America",
    tier: 3,
    bias: "River",
    icon: require("./images/civIcons/america.png"),
  },
  {
    civ: "Austria",
    tier: 3,
    bias: "Hills",
    icon: require("./images/civIcons/austria.png"),
  },
  {
    civ: "Denmark",
    tier: 3,
    bias: "Coast",
    icon: require("./images/civIcons/denmark.png"),
  },
  {
    civ: "Sweden",
    tier: 4,
    bias: "Tundra",
    icon: require("./images/civIcons/sweden.png"),
  },
  {
    civ: "Brazil",
    tier: 4,
    bias: "Jungle",
    icon: require("./images/civIcons/brazil.png"),
  },
  {
    civ: "Assyria",
    tier: 4,
    bias: "Avoid Tundra",
    icon: require("./images/civIcons/assyria.png"),
  },
  {
    civ: "Morocco",
    tier: 4,
    bias: "Desert",
    icon: require("./images/civIcons/morocco.png"),
  },
  {
    civ: "Portugal",
    tier: 4,
    bias: "Coast",
    icon: require("./images/civIcons/portugal.png"),
  },
  {
    civ: "Carthage",
    tier: 5,
    bias: "Coast",
    icon: require("./images/civIcons/carthage.png"),
  },
  {
    civ: "Netherlands",
    tier: 5,
    bias: "Grassland",
    icon: require("./images/civIcons/netherlands.png"),
  },
  {
    civ: "France",
    tier: 5,
    bias: "None",
    icon: require("./images/civIcons/france.png"),
  },
  {
    civ: "Japan",
    tier: 5,
    bias: "Coast",
    icon: require("./images/civIcons/japan.png"),
  },
  {
    civ: "Polynesia",
    tier: 5,
    bias: "Coast",
    icon: require("./images/civIcons/polynesia.png"),
  },
  {
    civ: "Ottomans",
    tier: 5,
    bias: "Coast",
    icon: require("./images/civIcons/ottoman.png"),
  },
  {
    civ: "Iroquois",
    tier: 6,
    bias: "Forest",
    icon: require("./images/civIcons/iroquois.png"),
  },
  {
    civ: "Venice",
    tier: 6,
    bias: "Coast",
    icon: require("./images/civIcons/venice.png"),
  },
];

export default listOfCivs;
